# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres # Replace with your Supabase database name
  username: postgres.besmvpuwxgaknczhukso # Replace with your Supabase database user
  password: <%= ENV['SUPABASE_DATABASE_PASSWORD'] %> # It's best to use environment variables for sensitive info
  host: aws-0-ca-central-1.pooler.supabase.com # Replace with your Supabase database host
  port: 5432 # Replace with your Supabase database port

test:
  <<: *default
  database: my_crud_app_test
  username: <%= ENV['SUPABASE_DATABASE_USER'] %>
  password: <%= ENV['SUPABASE_DATABASE_PASSWORD'] %>
  host: <%= ENV['SUPABASE_DATABASE_HOST'] %>
  port: <%= ENV['SUPABASE_DATABASE_PORT'] %>

production:
  <<: *default
  database: my_crud_app_production
  username: <%= ENV['SUPABASE_DATABASE_USER'] %>
  password: <%= ENV['SUPABASE_DATABASE_PASSWORD'] %>
  host: <%= ENV['SUPABASE_DATABASE_HOST'] %>
  port: <%= ENV['SUPABASE_DATABASE_PORT'] %>

# Explanation:
# - This file configures the database connection for your Rails application.
# - We've set the adapter to 'postgresql' to match Supabase.
# - Replace the placeholder values (your_supabase_database_name, user, host, port)
#   with your actual Supabase connection details.
# - It's highly recommended to use environment variables (like ENV['SUPABASE_DATABASE_PASSWORD'])
#   for sensitive information like passwords, especially in production. You'll need to set these
#   variables in your development environment (e.g., using a `.env` file and a gem like `dotenv-rails`)
#   and on your production server.
